name: Run go mod tidy
on:
  schedule:
    # Do this every week on Friday moring
    - cron: '0 7 * * FRI'

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: go mod tidy
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: go mod tidy
          title: Run go mod tidy
          branch: auto-go-mod-tidy
